name: RDP-VPS

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://drive.google.com/uc?id=1D8r4RtIUTM-QpWbsm34T6x97L3ZBhM8p  -OutFile nssm.exe
        Expand-Archive ngrok.zip
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy .\ngrok\ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://drive.google.com/uc?id=1lPEeX0ea_p8J6V3eAxbs2wZCuyokQzPV  -OutFile NGROK-AP.bat
        Invoke-WebRequest https://drive.google.com/uc?id=17zYTeOELIwzAxbosJJJc4Q3MypELq5ie  -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://drive.google.com/uc?id=1jite_VgKqUjfIr6nfZ55spbsA9dm2Y8k  -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: cmd /c ngrok.exe tcp 3389 & NGROK-CHECK.bat &
    - run: cmd /c loop.bat
